# Generated by Django 2.1.2 on 2020-03-17 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 19, 19, 41, 27626), verbose_name='Date Published'),
        ),
    ]
